### PR TITLE
Update billing to XRechnung 2.2.0

### PR DESCRIPTION
**Pull request by jakob-p**
# Pull Request

### Description
+ Update billing to XRechnung 2.2.0

### Addresses
https://github.com/alex-therapeutics/diga-api-client/issues/115

### CODE REVIEW

**Comment by jakob-p** [comment]
this PR  also includes the changes for the v3-support branch as no endpoint uses the old version anymore, so it can updated on main.

**Comment by jakob-p** [comment]
@fongie  Can you create a release based on this PR to enable XRechnung 2.2.0 ?

**Comment by fongie** [comment]
Thanks for opening the PR! I will get to it

**Review by fongie — CHANGES_REQUESTED** [review]
Thank you for working on this! When I run my test requests from your PR, the code validation request goes through, but when trying the billing one I get:

```
Exception in thread "main" java.lang.NullPointerException
	at com.alextherapeutics.diga.implementation.DigaXmlJaxbRequestReader.getInvoiceErrors(DigaXmlJaxbRequestReader.java:157)
	at com.alextherapeutics.diga.implementation.DigaXmlJaxbRequestReader.readBillingReport(DigaXmlJaxbRequestReader.java:76)
	at com.alextherapeutics.diga.DigaApiClient.performDigaInvoicingAgainstApi(DigaApiClient.java:294)
	at com.alextherapeutics.diga.DigaApiClient.performDigaInvoicing(DigaApiClient.java:256)
	at com.alextherapeutics.diga.DigaApiClient.sendTestInvoiceRequest(DigaApiClient.java:199)
	at com.alextherapeutics.Main.main(Main.java:135)
```

This seems to be because when we fetch the response of the invoice request, the `Report.scenarioMatched` is `null`, which we use to create information about why the response failed at `DigaXmlJaxbRequestReader#157`

Is it working for you to send invoice requests? Could you look at this and see if can be fixed, maybe we need to update some other xsd..?

**Comment by jakob-p** [comment]
Its working for me for the TK Endpoint, they already validate the XRechnung 2.2.0 

**only for testing, for real invoices it should not be used before october**

				
```DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
				String cunvertCurrentDate="2023-09-04";
				Date date = new Date();
				date = df.parse(cunvertCurrentDate);

				digaInvoice  = DigaInvoice.builder()
						.invoiceId("INVOICE123")
						.validatedDigaCode("77AAAAAAAAAAAAAX")
						.dateOfServiceProvision(date)
						.digavEid("12345678")
						.build();
				invoiceDiga = apiClient.sendTestInvoiceRequest(digaInvoice,"DM");
				//invoiceDiga = apiClient.invoiceDiga(digaInvoice);
				System.out.println(invoiceDiga.getGeneratedInvoice());
				System.out.println("#############################");
				System.out.println(invoiceDiga.getErrors());
```

If i try other endpoints i get the same error as you. It seems if something goes wrong, the error handling is broken...

I used this example to change the XRechnung generation:

https://github.com/ITSGGMBH/validator-configuration-diga/blob/main/src/test/resources/dre0/xrechnung-2.2-valid_normal.xml

i did not touch the XSD files yet, can we use something from https://github.com/ITSGGMBH/validator-configuration-diga/tree/main ?

**Comment by jakob-p** [comment]
I tried but i cant figure out how to fix the Report.scenarioMatched ... do you know how to fix it @fongie   ?

**Comment by fongie** [comment]
I have an idea, Ill be back with it shortly (hopefully)

**Comment by fongie** [comment]
@jakob-p I have made a PR to your fork branch here https://github.com/jakob-p/diga-api-client/pull/1 which should fix the issue I had. Please review and add to this PR if approved

Next, I'm thinking about how to version this release. Since the library will in fact not work with any insurance APIs before the deadline (if I understood correctly), I think we should either make a beta or "preview" release or a major version upgrade (2.0), so library users can choose how to deal with being ready to switch when insurance APIs are ready. If I make a normal release someone might upgrade their version and break their integration. What do you think?

**Comment by jakob-p** [comment]
Thank you for the fix @fongie, yes the error handling now works if no scenario was matched.

But i am seeing some new validation errors when trying to submit the test XRechnung 2.2.0 to TK.  I think they added some rules, i will need to check this next week again.

I agree releasing this as beta release until all endpoints accept the new version.

**Comment by jakob-p** [comment]
actually i think TK just stopped accepting XRechnung 2.2.0 in their test billing, but i will double check that my changes for XRechnung 2.2.0 are valid next week

**Review by jakob-gh — APPROVED** [review]

**Comment by jakob-p** [comment]
I added small change to make it valid against the Kosit validator DiGA XRechnung2.2.0 configuration:

grafik

At the moment we can not test it against the real endpoints, but i would say it is ready for the beta release now as the validator accepts the generated bill as valid XRechnung2.2.0

**Comment by fongie** [comment]
Good! I am getting some errors from TK but we don't really know what they're up to I guess, as usual, on the insurance endpoint side. I still consider this to be a bit experimental though, so I will release version `2.0.0-alpha.1` and make it clear in the changelog that this has not really been tested, but is made available to give you guys with live digas (.. which we are not yet) a chance to be ready when the insurances switch

It would be great though if someone could try their hand at the other billing api updates in #115 as well. If I have some inspiration I might go for it but since we're not live yet I won't give it prio. Id be happy to help with reviewing etc. if someone got started on it.

The condition for releasing 2.0.0 (without alpha tags) I think is to have both the new billing APIs and the new Xrechnung spec supported, and confirmation that they are working against at least a few endpoints

**Comment by fongie** [comment]
I have released 1.2.6 which moves us to v3 schemas and includes depency updates. Note that it does not contain the code in this PR, I will notify you here when that is released

**Review by fongie — APPROVED** [review]

**Comment by fongie** [comment]
released in https://github.com/alex-therapeutics/diga-api-client/releases/tag/2.0.0-beta.1

**Comment by jakob-p** [comment]
Thank you for the release @fongie  ! I will test it and let you know if everything is working as expected.

For the other API changes i unfortunatly currently dont have ressources, i will only be able to check them in a few months.

**Pull request merged**
